### ISSUE TITLE
Loading catalog failes under https

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia-json-extension#4]
The page at 'https://workspace.com/4711' was loaded over HTTPS, but requested an insecure resource 'http://schemastore.org/api/json/catalog.json'. This request has been blocked; the content must be served over HTTPS.

**Comment by AlexTugarev** [comment]
`https://schemastore.org/api/json/catalog.json` has an invalid certificate. maybe it will still work.

**Comment by AlexTugarev** [comment]
`https://schemastore.azurewebsites.net/api/json/catalog.json` is the "real" location we could use. see https://github.com/SchemaStore/schemastore/issues/12#issuecomment-190398346
